# config/mosquitto.conf
user root

listener 1883
allow_anonymous false
password_file /mosquitto/config/pwfile

persistence true
persistence_location /mosquitto/data/

# --- NEW LOGGING RULES ---
log_dest stdout
log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
connection_messages true