version: '3.8'
services:
  mongodb:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influx_data:/var/lib/influxdb2

volumes:
  mongo_data:
  influx_data: